package scryfallapi

// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

import (
    "context"
    "go"
    "github.com/satori/go.uuid"
)

        // SetsClientAPI contains the set of methods on the SetsClient type.
        type SetsClientAPI interface {
            GetAll(ctx context.Context) (result scryfall.SetList, err error)
            GetByCode(ctx context.Context, code string) (result scryfall.Set, err error)
        }

        var _ SetsClientAPI = (*scryfall.SetsClient)(nil)
        // CardsClientAPI contains the set of methods on the CardsClient type.
        type CardsClientAPI interface {
            Autocomplete(ctx context.Context, q string) (result scryfall.Catalog, err error)
            GetByArenaID(ctx context.Context, ID int32) (result scryfall.Card, err error)
            GetByCodeByNumber(ctx context.Context, code string, number int32) (result scryfall.Card, err error)
            GetByID(ctx context.Context, ID uuid.UUID) (result scryfall.Card, err error)
            GetByMtgoID(ctx context.Context, ID int32) (result scryfall.Card, err error)
            GetByMultiverseID(ctx context.Context, ID int32) (result scryfall.Card, err error)
            GetNamed(ctx context.Context, exact string, fuzzy string, set string, formatParameter string, face string, version string, pretty *bool) (result scryfall.Card, err error)
            GetRandom(ctx context.Context) (result scryfall.Card, err error)
            Search(ctx context.Context, q string, unique scryfall.UniqueStrategy, order scryfall.SortOrder, dir scryfall.SortDirection, includeExtras *bool, page *int32) (result scryfall.CardList, err error)
        }

        var _ CardsClientAPI = (*scryfall.CardsClient)(nil)
        // RulingsClientAPI contains the set of methods on the RulingsClient type.
        type RulingsClientAPI interface {
            GetByCodeByNumberID(ctx context.Context, code string, number int32) (result scryfall.RulingList, err error)
            GetByID(ctx context.Context, ID uuid.UUID) (result scryfall.RulingList, err error)
            GetByMtgoID(ctx context.Context, ID int32) (result scryfall.RulingList, err error)
            GetByMultiverseID(ctx context.Context, ID int32) (result scryfall.RulingList, err error)
        }

        var _ RulingsClientAPI = (*scryfall.RulingsClient)(nil)
        // SymbologyClientAPI contains the set of methods on the SymbologyClient type.
        type SymbologyClientAPI interface {
            GetAll(ctx context.Context) (result scryfall.CardSymbolList, err error)
            ParseMana(ctx context.Context, cost string) (result scryfall.ManaCost, err error)
        }

        var _ SymbologyClientAPI = (*scryfall.SymbologyClient)(nil)
        // CatalogClientAPI contains the set of methods on the CatalogClient type.
        type CatalogClientAPI interface {
            GetArtifactTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetCardNames(ctx context.Context) (result scryfall.Catalog, err error)
            GetCreatureTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetEnchantmentTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetLandTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetLoyalties(ctx context.Context) (result scryfall.Catalog, err error)
            GetPlaneswalkerTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetPowers(ctx context.Context) (result scryfall.Catalog, err error)
            GetSpellTypes(ctx context.Context) (result scryfall.Catalog, err error)
            GetToughnesses(ctx context.Context) (result scryfall.Catalog, err error)
            GetWatermarks(ctx context.Context) (result scryfall.Catalog, err error)
            GetWordBank(ctx context.Context) (result scryfall.Catalog, err error)
        }

        var _ CatalogClientAPI = (*scryfall.CatalogClient)(nil)
